---
- name: Create folders
  ansible.builtin.file:
    path: /home/manyfold/{{ item }}
    owner: manyfold
    group: manyfold
    state: directory
    mode: '0775'
  loop:
    - libraries
    - config
    - sys-tmp
    - app-tmp
    - log

- name: Manyfold Network
  community.docker.docker_network:
    name: manyfold
    enable_ipv6: true

- name: Manyfold
  community.docker.docker_container:
    name: manyfold
    image: "ghcr.io/manyfold3d/manyfold-solo:latest"
    pull: yes
    restart_policy: unless-stopped
    env:
      PUID: "{{ getent_passwd['manyfold'][1] }}"
      PGID: "{{ getent_passwd['manyfold'][2] }}"
      SECRET_KEY_BASE: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=64') }}"
      PUBLIC_HOSTNAME: "try.manyfold.app"
      PUBLIC_PORT: "443"
      DEMO_MODE: "enabled"
      FEDERATION: "enabled"
      HTTPS_ONLY: "enabled"
      SITE_NAME: "Try Manyfold"
      SITE_TAGLINE: "The official Manyfold demo instance"
    read_only: true
    security_opts:
     - no-new-privileges:true
    cap_drop:
      - ALL
    capabilities:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
      - SYS_ADMIN
    tmpfs:
      - /run:exec
    mounts:
      - type: bind
        source: /home/manyfold/config
        target: /config
        read_only: false
      - type: bind
        source: /home/manyfold/libraries
        target: /libraries
        read_only: false
      - type: bind
        source: /home/manyfold/sys-tmp
        target: /tmp
        read_only: false
      - type: bind
        source: /home/manyfold/app-tmp
        target: /usr/src/app/tmp
        read_only: false
      - type: bind
        source: /home/manyfold/log
        target: /usr/src/app/log
        read_only: false
    networks:
      - name: "manyfold"
