---
- name: Create folders
  ansible.builtin.file:
    path: /home/manyfold/{{ item }}
    owner: manyfold
    group: manyfold
    state: directory
    mode: '0775'
  loop:
    - config
    - log
    - storage/app-tmp
    - storage/libraries
    - storage/sys-tmp

- name: Manyfold
  community.docker.docker_container:
    name: manyfold
    image: "manyfold3d/manyfold:latest"
    pull: yes
    restart_policy: unless-stopped
    env:
      PUID: "{{ getent_passwd['manyfold'][1] }}"
      PGID: "{{ getent_passwd['manyfold'][2] }}"
      DATABASE_URL: postgresql://{{ postgres_username }}:{{ postgres_password }}@postgresql/{{ postgres_database }}
      REDIS_URL: redis://valkey:6379
      SECRET_KEY_BASE: "{{ secret_key_base }}"
      PUBLIC_HOSTNAME: "{{ public_hostname }}"
      PUBLIC_PORT: "443"
      MULTIUSER: "enabled"
      FEDERATION: "enabled"
      HTTPS_ONLY: "enabled"
      WEB_CONCURRENCY: "8"
      DEFAULT_WORKER_CONCURRENCY: "32"
      SMTP_USERNAME: "{{ smtp_username }}"
      SMTP_PASSWORD: "{{ smtp_password }}"
      SMTP_SERVER: "{{ smtp_server }}"
      MANYFOLD_LOG_LEVEL: debug
    read_only: true
    security_opts:
     - no-new-privileges:true
    cap_drop:
      - ALL
    capabilities:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
      - SYS_ADMIN
    tmpfs:
      - /run:exec
    mounts:
      - type: bind
        source: /home/manyfold/config
        target: /config
        read_only: false
      - type: bind
        source: /home/manyfold/storage/libraries
        target: /libraries
        read_only: false
      - type: bind
        source: /home/manyfold/storage/sys-tmp
        target: /tmp
        read_only: false
      - type: bind
        source: /home/manyfold/storage/app-tmp
        target: /usr/src/app/tmp
        read_only: false
      - type: bind
        source: /home/manyfold/log
        target: /usr/src/app/log
        read_only: false
    networks:
      - name: "manyfold"
